# ========================
# Server
# ========================
server.port=8080
server.id=producer-local

# ========================
# Jackson
# ========================
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# ========================
# RabbitMQ
# ========================
spring.rabbitmq.host=172.31.31.147
spring.rabbitmq.port=5672
spring.rabbitmq.username=cc
spring.rabbitmq.password=o3o4
rabbitmq.channel.pool.size=20

# ========================
# Room Configuration
# ========================
rabbitmq.rooms=20
rabbitmq.queue.message-ttl=60000
rabbitmq.queue.max-length=10000

# ========================
# Redis
# ========================
spring.data.redis.host=172.31.31.147
spring.data.redis.port=6379

# ========================
# Circuit Breaker RabbitMQ publish (producer side)
# ========================
resilience4j.circuitbreaker.instances.rabbitmq-publish.sliding-window-size=10
resilience4j.circuitbreaker.instances.rabbitmq-publish.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.rabbitmq-publish.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.rabbitmq-publish.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.rabbitmq-publish.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.rabbitmq-publish.permitted-number-of-calls-in-half-open-state=3